### ISSUE TITLE
Get oriented with the essentials of Terraform (and Ansible)

### ISSUE THREAD

**Issue by kltm** [geneontology/devops-documentation#1]
The two systems we elected to use for our devops are terraform and ansible. It might be good to get a little familiar.

Note that the devops we do are done within a docker image "go-dev". Information about setup and some background can be found here https://github.com/geneontology/devops-documentation/blob/main/README.setup.md and https://github.com/geneontology/devops-documentation/blob/main/README.general-operations.md

**Comment by kltm** [comment]
Talking @mugitty (and @dustine32 ), will start testing the devops/terraform/ansible stuff as above to get oriented.

**Comment by kltm** [comment]
Talking with @mugitty , we'll look at adding some "production" and "development"-specific templates to help simplify the documentation.

**Comment by kltm** [comment]
After the go-graphstore, another good (but with a slightly more "primitive" state of documentation) example would be the go-fastapi devops doc:
https://github.com/geneontology/go-fastapi/pull/90

**Comment by mugitty** [comment]
1. Created and destroyed internal and production graphstore instances by following directions on https://github.com/geneontology/devops-documentation/blob/main/README.graphstore.md.
2. Created branch https://github.com/geneontology/devops-documentation/tree/issue-1-update-documentation to update documentation. Proposed changes are reflected in this branch

**Comment by mugitty** [comment]
Plan to create and destroy instances of the go-fastapi following instructions from branch https://github.com/geneontology/go-fastapi/tree/project-management-85-pass-w-ssd
